# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: LangHuiHE
          template: classic
          base: header, activity, community, repositories
          config_timezone: America/Denver
          #
          plugin_introduction: yes
          plugin_introduction_title: yes
          #
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          #
          plugin_repositories: 100
          plugin_repositories_affiliations: owner
          plugin_repositories_batch: 100
          #
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          #
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          #
          plugin_followup: yes
          plugin_followup_sections: repositories, user # Display overall status of issues/pull requests created on user's repositories and created by user
          #
          plugin_activity: yes
          plugin_activity_limit: 5           # Limit to 5 events
          plugin_activity_load: 100          # Load up to 100 recent events from API (should be higher than "limit")
          plugin_activity_days: 14           # Keep only events from last 14 days (set to 0 for no limit)
          plugin_activity_filter: all        # Show all events (use table above to filter events types)
          plugin_activity_visibility: public # Only display public events
          plugin_activity_timestamps: yes    # Display events timestamps
          plugin_activity_skipped: repo      # Ignored repositories
          #
