# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: LangHuiHE
          template: classic
          base: header, activity, community, repositories
          config_timezone: America/Denver
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css, TeX, Makefile            # List of languages to ignore
          plugin_languages_skipped: my-test-repo                        # List of repositories to skip
          plugin_languages_limit: 15                                    # Display up to 8 languages
          plugin_languages_sections: most-used #recently-used           # Display most used and recently used
          plugin_languages_threshold: 0%                                # Hides all languages less than 0% 
          # languages stats
          plugin_languages_indepth: no                                  # Get indepth stats (see documentation before enabling)
          plugin_languages_analysis_timeout: 15                         # Set maximum time for indepth analysis
          plugin_languages_categories: programming                      # Display only languages that match these categories in most-used section
